pipeline {
  agent any

  environment {
    DOCKER_CREDS = credentials('dockerhub_creds')
  }

  stages {
    stage('Clone repo') {
      steps {
        git branch: 'main', url: 'https://github.com/narang24/microservices-vn',credentialsId: 'github-creds'
      }
    }
    stage('Build docker image') {
      steps {
        bat '''
          docker build -t narang24/auth-service:${GIT_COMMIT} services/auth-service
        '''
      }
    }
    stage('Push docker image') {
      steps {
        bat '''
          echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --password-stdin
          docker push narang24/auth-service:${GIT_COMMIT}
        '''
      }
    }
    stage('Update helm values') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'github-creds',
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) 
        {
          bat '''
          git config user.name "narang24"
          git config user.email "narang24@gmail.com"

          sed -i "s/tag:.*/tag: ${GIT_COMMIT}/" helm/auth/values.yaml
          git add helm/auth/values.yaml
          git commit -m "ci: update auth image tag"
          git push https://${GIT_USER}:${GIT_TOKEN}@github.com/narang24/microservices-vn.git main
          '''
        }
      }
    }
  }
}